### ISSUE TITLE
 gen_tec_xml: from excel file with empty columns

### ISSUE THREAD

**Issue by helraynal** [SticsRPacks/SticsOnR#15]
Hello
when I generate a set of tec files from an excel file with empty columns for tillage or irrigation, I have by default nb_intervention different from 0. When I filled only one line of these columns with values, nb_intervention is correct  for all the tec files of the usms
Helene
---

**Comment by plecharpent** [comment]
Hi Hélène,
Could you please post your issue in the appropriate package her https://github.com/SticsRPacks/SticsRFiles/issues and attach your Excel file please.
Thanks.
Regards.
